# Introduction to pandas  
- Pandas is a Python library used for data analysis, data cleaning and data manipulation.  
- It helps us work with structured data especially data in table form, similar to Excel, SQL tables or CSV files.  

_Analogy_ Pandas is a Python Excel.   

In pandas you can:  
- Open data
- Filter through the data  
- Create new columns  
- Clean missing values  
- Sort data  
- Group data  
- Do calculations on the data.  

## Main Data Structures in Pandas  
### a). Series.  
A Series is like a single column in Excel.

In [79]:
import pandas as pd
students = {'Name':['Mark', 'Allan', 'Bill', 'Renee', 'Mash', 'Michael', 'Jules', 'Sam', 'Steven']}
student_names = pd.Series(students)

student_names.head()

Name    [Mark, Allan, Bill, Renee, Mash, Michael, Jule...
dtype: object

### b). DataFrame.  
A DataFrame is like a full table with rows and columns.  
A DataFrame is a 2 dimensional data.

In [80]:
students = {'Name':['Mark', 'Allan', 'Bill', 'Renee', 'Mash', 'Michael', 'Jules', 'Sam', 'Steven'],
 'Grade':['A', 'B', 'B', 'A', 'C', 'C', 'B', 'A', 'B'],
 'Course':['DS', 'DE', 'DS', 'DS', 'DE', 'DE', 'DS', 'DS', 'DE']}  

student_grades = pd.DataFrame(students)  

student_grades

      Name Grade Course
0     Mark     A     DS
1    Allan     B     DE
2     Bill     B     DS
3    Renee     A     DS
4     Mash     C     DE
5  Michael     C     DE
6    Jules     B     DS
7      Sam     A     DS
8   Steven     B     DE

## Reading using pandas  
CSV  

```python  
df = pd.read_csv("C:\Users\mbaab\Downloads\nairobi_housing_statistics_dataset.csv")
```  

Excel File  
```python  
df = pd.read_excel("C:\Users\mbaab\Downloads\nairobi_housing_statistics_dataset.xlsx")  
``` 
SQL  
```python 
from sqlalchemy import create_engine

engine = create_engine("postgresql+psycopg2://username:password@localhost:port/dbname")
df = pd.read_sql_table("employee", con=engine)  

df = pd.read_sql("SELECT Name, Age FROM employee", con=engine)
```

In [81]:
# Reading the Housing 
import pandas as pd
df = pd.read_csv(r"C:\Users\mbaab\OneDrive\Desktop\Training projects & Repositories\Notebooks\Statistics\nairobi_housing_statistics_dataset.csv")

In [82]:
# Viewing the first five entries/rows
print(f"First five rows:  {display(df.head())}")  

# Viewing the last five entries  
print(f"Last five rows: {display(df.tail())}")

,property_id,estate,property_type,furnishing,bedrooms,bathrooms,floor_size_sqm,monthly_rent_kes,service_charge_kes,distance_to_cbd_km,...,security_rating,occupancy_rate,parking_slots,has_backup_generator,has_borehole,tenant_type,vacancy_status,satisfaction_score,rent_2024,rent_2025
0,1,South B,Apartment,Unfurnished,3,2,114.8,174906.0,5549.0,9.9,...,6.5,93.5,2,Yes,No,Professional,Occupied,71.2,153825.0,174906.0
1,2,Karen,Apartment,Semi-Furnished,5,5,75.2,377170.0,3205.0,24.5,...,6.9,94.0,3,No,Yes,Professional,Occupied,89.4,336858.0,377170.0
2,3,Umoja,Apartment,Furnished,1,1,84.9,84013.0,4526.0,6.6,...,7.9,91.2,0,No,No,Student,Occupied,83.1,71889.0,84013.0
3,4,Ruaka,Apartment,Unfurnished,2,3,75.2,151752.0,2496.0,17.9,...,6.6,98.6,2,No,Yes,Student,Occupied,65.4,137138.0,151752.0
4,5,Kasarani,Maisonette,Unfurnished,3,3,69.6,98368.0,999.0,3.6,...,6.9,94.0,2,No,No,Expat,Occupied,70.8,91765.0,98368.0

First five rows:  None

,property_id,estate,property_type,furnishing,bedrooms,bathrooms,floor_size_sqm,monthly_rent_kes,service_charge_kes,distance_to_cbd_km,...,security_rating,occupancy_rate,parking_slots,has_backup_generator,has_borehole,tenant_type,vacancy_status,satisfaction_score,rent_2024,rent_2025
1995,1996,Roysambu,Bedsitter,Unfurnished,5,5,88.6,178613.0,5780.0,13.6,...,5.3,94.2,3,Yes,Yes,Expat,Occupied,60.4,165861.0,178613.0
1996,1997,Langata,Apartment,Unfurnished,4,3,81.1,174164.0,5301.0,15.1,...,7.9,92.7,3,No,Yes,Professional,Occupied,67.5,161015.0,174164.0
1997,1998,South C,Townhouse,Furnished,5,6,84.4,205602.0,2309.0,3.5,...,8.0,87.7,3,No,No,Family,Occupied,78.7,178594.0,205602.0
1998,1999,Roysambu,Apartment,Furnished,2,1,78.9,114482.0,4227.0,7.7,...,5.8,88.1,1,No,Yes,Family,Occupied,73.4,99874.0,114482.0
1999,2000,Ruaka,Apartment,Unfurnished,4,4,97.8,256507.0,NaN,21.1,...,9.6,88.8,3,Yes,No,Student,Occupied,79.6,240198.0,256507.0

Last five rows: None

In [83]:
# Checking the number of rows and columns  
df.shape

(2000, 21)

In [84]:
# Viewing column names  
df.columns

# Convert ing columns to a list
property = df.columns.tolist()  

property

['property_id',
 'estate',
 'property_type',
 'furnishing',
 'bedrooms',
 'bathrooms',
 'floor_size_sqm',
 'monthly_rent_kes',
 'service_charge_kes',
 'distance_to_cbd_km',
 'age_of_building_years',
 'security_rating',
 'occupancy_rate',
 'parking_slots',
 'has_backup_generator',
 'has_borehole',
 'tenant_type',
 'vacancy_status',
 'satisfaction_score',
 'rent_2024',
 'rent_2025']

In [85]:
property.remove("rent_2025")

In [86]:
# Viewing the general information of the dataset  
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2000 entries, 0 to 1999
Data columns (total 21 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   property_id            2000 non-null   int64
 1   estate                 2000 non-null   object
 2   property_type          2000 non-null   object
 3   furnishing             2000 non-null   object
 4   bedrooms               2000 non-null   int64
 5   bathrooms              2000 non-null   int64
 6   floor_size_sqm         2000 non-null   float64
 7   monthly_rent_kes       2000 non-null   float64
 8   service_charge_kes     1970 non-null   float64
 9   distance_to_cbd_km     2000 non-null   float64
 10  age_of_building_years  2000 non-null   float64
 11  security_rating        1970 non-null   float64
 12  occupancy_rate         2000 non-null   float64
 13  parking_slots          2000 non-null   int64
 14  has_backup_generator   2000 non-null   object
 15  has_borehole           2000 non-null   object
 16  tenant_type            2000 non-null   object
 17  vacancy_status         2000 non-null   object
 18  satisfaction_score     1970 non-null   float64
 19  rent_2024              2000 non-null   float64
 20  rent_2025              2000 non-null   float64
dtypes: float64(10), int64(4), object(7)
memory usage: 328.3+ KB

In [87]:
# Summary statistics
# Numerical columns (int and float)  
df.describe().T

,count,mean,std,min,25%,50%,75%,max
property_id,2000.0,1000.500000,577.494589,1.0,500.75,1000.5,1500.250,2000.0
bedrooms,2000.0,3.400500,1.446771,1.0,2.00,3.0,4.000,6.0
bathrooms,2000.0,3.407500,1.537734,1.0,2.00,3.0,5.000,6.0
floor_size_sqm,2000.0,84.535700,15.392019,-20.0,74.60,84.6,94.900,131.6
monthly_rent_kes,2000.0,223196.042500,180798.600091,-10000.0,129188.25,190307.5,287698.250,5000000.0
service_charge_kes,1970.0,4991.145178,4250.773577,498.0,2445.00,3881.0,6152.000,81569.0
distance_to_cbd_km,2000.0,10.299500,6.455535,0.4,5.50,8.9,13.600,47.6
age_of_building_years,2000.0,12.040350,5.825776,0.0,7.90,12.0,16.100,33.7
security_rating,1970.0,7.041929,1.208691,2.1,6.20,7.1,7.900,10.0
occupancy_rate,2000.0,89.987400,7.030065,38.0,86.50,91.7,95.300,99.9
parking_slots,2000.0,2.205000,0.924880,0.0,2.00,2.0,3.000,4.0
satisfaction_score,1970.0,75.031269,10.033413,38.8,68.20,75.2,82.175,100.0
rent_2024,2000.0,197121.745000,98598.381747,51867.0,117756.25,173361.0,259789.000,618802.0
rent_2025,2000.0,217312.541500,108001.488354,60067.0,129278.25,189898.5,287015.250,652410.0

In [88]:
# Categorical columns  
df.describe(include="object").T

                     count unique           top  freq
estate                2000     15     Westlands   159
property_type         2000      4     Apartment  1092
furnishing            2000      3   Unfurnished  1007
has_backup_generator  2000      2            No  1153
has_borehole          2000      2           Yes  1092
tenant_type           2000      4  Professional   521
vacancy_status        2000      2      Occupied  1670

__Selecting columns__

In [89]:
df.columns

Index(['property_id', 'estate', 'property_type', 'furnishing', 'bedrooms',
       'bathrooms', 'floor_size_sqm', 'monthly_rent_kes', 'service_charge_kes',
       'distance_to_cbd_km', 'age_of_building_years', 'security_rating',
       'occupancy_rate', 'parking_slots', 'has_backup_generator',
       'has_borehole', 'tenant_type', 'vacancy_status', 'satisfaction_score',
       'rent_2024', 'rent_2025'],
      dtype='object')

In [90]:
# Filtering columns
desired_columns = ['estate', 'property_type', 'furnishing', 'bedrooms']
stripped_df = df[desired_columns]  

stripped_df.head()

     estate property_type      furnishing  bedrooms
0   South B     Apartment     Unfurnished         3
1     Karen     Apartment  Semi-Furnished         5
2     Umoja     Apartment       Furnished         1
3     Ruaka     Apartment     Unfurnished         2
4  Kasarani    Maisonette     Unfurnished         3

__Selecting rows__

In [91]:
# Filtering/selecting the first row  
df.loc[[1]]

,property_id,estate,property_type,furnishing,bedrooms,bathrooms,floor_size_sqm,monthly_rent_kes,service_charge_kes,distance_to_cbd_km,...,security_rating,occupancy_rate,parking_slots,has_backup_generator,has_borehole,tenant_type,vacancy_status,satisfaction_score,rent_2024,rent_2025
1,2,Karen,Apartment,Semi-Furnished,5,5,75.2,377170.0,3205.0,24.5,...,6.9,94.0,3,No,Yes,Professional,Occupied,89.4,336858.0,377170.0

In [92]:
df.head()

,property_id,estate,property_type,furnishing,bedrooms,bathrooms,floor_size_sqm,monthly_rent_kes,service_charge_kes,distance_to_cbd_km,...,security_rating,occupancy_rate,parking_slots,has_backup_generator,has_borehole,tenant_type,vacancy_status,satisfaction_score,rent_2024,rent_2025
0,1,South B,Apartment,Unfurnished,3,2,114.8,174906.0,5549.0,9.9,...,6.5,93.5,2,Yes,No,Professional,Occupied,71.2,153825.0,174906.0
1,2,Karen,Apartment,Semi-Furnished,5,5,75.2,377170.0,3205.0,24.5,...,6.9,94.0,3,No,Yes,Professional,Occupied,89.4,336858.0,377170.0
2,3,Umoja,Apartment,Furnished,1,1,84.9,84013.0,4526.0,6.6,...,7.9,91.2,0,No,No,Student,Occupied,83.1,71889.0,84013.0
3,4,Ruaka,Apartment,Unfurnished,2,3,75.2,151752.0,2496.0,17.9,...,6.6,98.6,2,No,Yes,Student,Occupied,65.4,137138.0,151752.0
4,5,Kasarani,Maisonette,Unfurnished,3,3,69.6,98368.0,999.0,3.6,...,6.9,94.0,2,No,No,Expat,Occupied,70.8,91765.0,98368.0

__Filtering using row index and column name__

In [93]:
df.loc[4, "property_type"]

'Maisonette'

__Using iloc__

In [94]:
df.iloc[[0, 20, 40]]

,property_id,estate,property_type,furnishing,bedrooms,bathrooms,floor_size_sqm,monthly_rent_kes,service_charge_kes,distance_to_cbd_km,...,security_rating,occupancy_rate,parking_slots,has_backup_generator,has_borehole,tenant_type,vacancy_status,satisfaction_score,rent_2024,rent_2025
0,1,South B,Apartment,Unfurnished,3,2,114.8,174906.0,5549.0,9.9,...,6.5,93.5,2,Yes,No,Professional,Occupied,71.2,153825.0,174906.0
20,21,Lavington,Bedsitter,Furnished,2,1,106.9,273452.0,3877.0,24.8,...,6.6,64.2,2,Yes,Yes,Professional,Occupied,71.7,237241.0,273452.0
40,41,Ruaka,Apartment,Furnished,3,4,73.3,223925.0,5000.0,14.8,...,9.3,95.2,2,Yes,Yes,Professional,Occupied,61.6,190801.0,223925.0

In [95]:
# Selecting entries using row index and column index
df.iloc[4, -1]

np.float64(98368.0)

__Filtering Data using greater than, less than, greater than or equal to and vice versa__

In [96]:
# Filtering the dataset to only monthly rent greater than 50,000kes  
rent = df[df["monthly_rent_kes"] > 50000]

rent.head()

,property_id,estate,property_type,furnishing,bedrooms,bathrooms,floor_size_sqm,monthly_rent_kes,service_charge_kes,distance_to_cbd_km,...,security_rating,occupancy_rate,parking_slots,has_backup_generator,has_borehole,tenant_type,vacancy_status,satisfaction_score,rent_2024,rent_2025
0,1,South B,Apartment,Unfurnished,3,2,114.8,174906.0,5549.0,9.9,...,6.5,93.5,2,Yes,No,Professional,Occupied,71.2,153825.0,174906.0
1,2,Karen,Apartment,Semi-Furnished,5,5,75.2,377170.0,3205.0,24.5,...,6.9,94.0,3,No,Yes,Professional,Occupied,89.4,336858.0,377170.0
2,3,Umoja,Apartment,Furnished,1,1,84.9,84013.0,4526.0,6.6,...,7.9,91.2,0,No,No,Student,Occupied,83.1,71889.0,84013.0
3,4,Ruaka,Apartment,Unfurnished,2,3,75.2,151752.0,2496.0,17.9,...,6.6,98.6,2,No,Yes,Student,Occupied,65.4,137138.0,151752.0
4,5,Kasarani,Maisonette,Unfurnished,3,3,69.6,98368.0,999.0,3.6,...,6.9,94.0,2,No,No,Expat,Occupied,70.8,91765.0,98368.0

In [97]:
rent2 = df[df["monthly_rent_kes"] < 50000]

rent2.head()

,property_id,estate,property_type,furnishing,bedrooms,bathrooms,floor_size_sqm,monthly_rent_kes,service_charge_kes,distance_to_cbd_km,...,security_rating,occupancy_rate,parking_slots,has_backup_generator,has_borehole,tenant_type,vacancy_status,satisfaction_score,rent_2024,rent_2025
1054,1055,Ruaka,Apartment,Unfurnished,1,1,66.3,-10000.0,2340.0,18.0,...,7.0,87.4,1,No,Yes,Family,Occupied,78.9,118081.0,137057.0
1161,1162,Roysambu,Apartment,Unfurnished,4,3,75.2,-5000.0,5562.0,11.4,...,7.0,99.0,2,No,Yes,Professional,Occupied,65.3,103340.0,118429.0

__Filtering Categorical values__   
Single condition.

In [98]:
# == Equals  
# != Not equal  
unfurnished = df[df["furnishing"] == "Unfurnished"]  
unfurnished

,property_id,estate,property_type,furnishing,bedrooms,bathrooms,floor_size_sqm,monthly_rent_kes,service_charge_kes,distance_to_cbd_km,...,security_rating,occupancy_rate,parking_slots,has_backup_generator,has_borehole,tenant_type,vacancy_status,satisfaction_score,rent_2024,rent_2025
0,1,South B,Apartment,Unfurnished,3,2,114.8,174906.0,5549.0,9.9,...,6.5,93.5,2,Yes,No,Professional,Occupied,71.2,153825.0,174906.0
3,4,Ruaka,Apartment,Unfurnished,2,3,75.2,151752.0,2496.0,17.9,...,6.6,98.6,2,No,Yes,Student,Occupied,65.4,137138.0,151752.0
4,5,Kasarani,Maisonette,Unfurnished,3,3,69.6,98368.0,999.0,3.6,...,6.9,94.0,2,No,No,Expat,Occupied,70.8,91765.0,98368.0
5,6,South C,Apartment,Unfurnished,2,2,67.0,120321.0,3397.0,17.0,...,6.6,96.3,2,No,No,Family,Occupied,66.3,110617.0,120321.0
7,8,Runda,Apartment,Unfurnished,3,2,55.5,360578.0,8250.0,2.8,...,6.6,95.1,3,Yes,Yes,Student,Occupied,72.5,339209.0,360578.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1993,1994,Donholm,Bedsitter,Unfurnished,1,1,89.4,111916.0,3363.0,5.6,...,5.0,94.4,1,Yes,No,Expat,Occupied,71.3,99549.0,111916.0
1994,1995,Runda,Apartment,Unfurnished,1,1,90.0,332358.0,8864.0,7.2,...,5.3,97.7,2,No,Yes,Expat,Occupied,84.3,313440.0,332358.0
1995,1996,Roysambu,Bedsitter,Unfurnished,5,5,88.6,178613.0,5780.0,13.6,...,5.3,94.2,3,Yes,Yes,Expat,Occupied,60.4,165861.0,178613.0
1996,1997,Langata,Apartment,Unfurnished,4,3,81.1,174164.0,5301.0,15.1,...,7.9,92.7,3,No,Yes,Professional,Occupied,67.5,161015.0,174164.0
1999,2000,Ruaka,Apartment,Unfurnished,4,4,97.8,256507.0,NaN,21.1,...,9.6,88.8,3,Yes,No,Student,Occupied,79.6,240198.0,256507.0

Multiple conditions  
_AND Condition_

In [99]:
# Filtering to only units located in Kasarani and they are unfurnished  
unfurnished_in_kasarani =  df[(df["estate"]=='Kasarani') & (df["furnishing"]=="Unfurnished")] 
unfurnished_in_kasarani.head()

,property_id,estate,property_type,furnishing,bedrooms,bathrooms,floor_size_sqm,monthly_rent_kes,service_charge_kes,distance_to_cbd_km,...,security_rating,occupancy_rate,parking_slots,has_backup_generator,has_borehole,tenant_type,vacancy_status,satisfaction_score,rent_2024,rent_2025
4,5,Kasarani,Maisonette,Unfurnished,3,3,69.6,98368.0,999.0,3.6,...,6.9,94.0,2,No,No,Expat,Occupied,70.8,91765.0,98368.0
39,40,Kasarani,Bedsitter,Unfurnished,3,3,83.8,105489.0,4994.0,4.5,...,7.4,82.4,1,No,Yes,Student,Occupied,91.4,93646.0,105489.0
210,211,Kasarani,Townhouse,Unfurnished,2,2,80.4,104439.0,4612.0,5.8,...,7.3,84.1,1,No,No,Professional,Occupied,82.8,100881.0,104439.0
238,239,Kasarani,Maisonette,Unfurnished,6,6,80.4,131080.0,1453.0,3.5,...,6.6,91.5,4,No,Yes,Family,Occupied,73.7,112705.0,131080.0
278,279,Kasarani,Apartment,Unfurnished,3,2,93.5,150667.0,2939.0,3.4,...,7.7,97.2,2,Yes,Yes,Expat,Occupied,67.1,131880.0,150667.0

_OR condition_

In [100]:
# OR condition, houses with unfurnished condition or located in Kasarani  
kasarani_unfurnished = df[(df["estate"]=='Kasarani') | (df["furnishing"]=='Unfurnished')]

kasarani_unfurnished

,property_id,estate,property_type,furnishing,bedrooms,bathrooms,floor_size_sqm,monthly_rent_kes,service_charge_kes,distance_to_cbd_km,...,security_rating,occupancy_rate,parking_slots,has_backup_generator,has_borehole,tenant_type,vacancy_status,satisfaction_score,rent_2024,rent_2025
0,1,South B,Apartment,Unfurnished,3,2,114.8,174906.0,5549.0,9.9,...,6.5,93.5,2,Yes,No,Professional,Occupied,71.2,153825.0,174906.0
3,4,Ruaka,Apartment,Unfurnished,2,3,75.2,151752.0,2496.0,17.9,...,6.6,98.6,2,No,Yes,Student,Occupied,65.4,137138.0,151752.0
4,5,Kasarani,Maisonette,Unfurnished,3,3,69.6,98368.0,999.0,3.6,...,6.9,94.0,2,No,No,Expat,Occupied,70.8,91765.0,98368.0
5,6,South C,Apartment,Unfurnished,2,2,67.0,120321.0,3397.0,17.0,...,6.6,96.3,2,No,No,Family,Occupied,66.3,110617.0,120321.0
7,8,Runda,Apartment,Unfurnished,3,2,55.5,360578.0,8250.0,2.8,...,6.6,95.1,3,Yes,Yes,Student,Occupied,72.5,339209.0,360578.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1993,1994,Donholm,Bedsitter,Unfurnished,1,1,89.4,111916.0,3363.0,5.6,...,5.0,94.4,1,Yes,No,Expat,Occupied,71.3,99549.0,111916.0
1994,1995,Runda,Apartment,Unfurnished,1,1,90.0,332358.0,8864.0,7.2,...,5.3,97.7,2,No,Yes,Expat,Occupied,84.3,313440.0,332358.0
1995,1996,Roysambu,Bedsitter,Unfurnished,5,5,88.6,178613.0,5780.0,13.6,...,5.3,94.2,3,Yes,Yes,Expat,Occupied,60.4,165861.0,178613.0
1996,1997,Langata,Apartment,Unfurnished,4,3,81.1,174164.0,5301.0,15.1,...,7.9,92.7,3,No,Yes,Professional,Occupied,67.5,161015.0,174164.0
1999,2000,Ruaka,Apartment,Unfurnished,4,4,97.8,256507.0,NaN,21.1,...,9.6,88.8,3,Yes,No,Student,Occupied,79.6,240198.0,256507.0

__Creating new columns__

In [101]:
# Add a column named monthly rent in USD from the monthly rent KES
df["monthly_rent_usd"]  = df["monthly_rent_kes"] / 130 

# Example
# Assume you want to get profit from  a sales and cost columns
# Profit = Sales - Cost
# df["profit"] = df["sales"] - df["cost"]

In [102]:
df.head()

,property_id,estate,property_type,furnishing,bedrooms,bathrooms,floor_size_sqm,monthly_rent_kes,service_charge_kes,distance_to_cbd_km,...,occupancy_rate,parking_slots,has_backup_generator,has_borehole,tenant_type,vacancy_status,satisfaction_score,rent_2024,rent_2025,monthly_rent_usd
0,1,South B,Apartment,Unfurnished,3,2,114.8,174906.0,5549.0,9.9,...,93.5,2,Yes,No,Professional,Occupied,71.2,153825.0,174906.0,1345.430769
1,2,Karen,Apartment,Semi-Furnished,5,5,75.2,377170.0,3205.0,24.5,...,94.0,3,No,Yes,Professional,Occupied,89.4,336858.0,377170.0,2901.307692
2,3,Umoja,Apartment,Furnished,1,1,84.9,84013.0,4526.0,6.6,...,91.2,0,No,No,Student,Occupied,83.1,71889.0,84013.0,646.253846
3,4,Ruaka,Apartment,Unfurnished,2,3,75.2,151752.0,2496.0,17.9,...,98.6,2,No,Yes,Student,Occupied,65.4,137138.0,151752.0,1167.323077
4,5,Kasarani,Maisonette,Unfurnished,3,3,69.6,98368.0,999.0,3.6,...,94.0,2,No,No,Expat,Occupied,70.8,91765.0,98368.0,756.676923

__Renaming columns(column names)__  
df = df.rename(columns={'old_name':'new_name'})

In [103]:
# Renaming has_backup_generator, property_id  

df = df.rename(columns={'has_backup_generator':'backup_generator',
                            'property_id':'id'})

df.head()

,id,estate,property_type,furnishing,bedrooms,bathrooms,floor_size_sqm,monthly_rent_kes,service_charge_kes,distance_to_cbd_km,...,occupancy_rate,parking_slots,backup_generator,has_borehole,tenant_type,vacancy_status,satisfaction_score,rent_2024,rent_2025,monthly_rent_usd
0,1,South B,Apartment,Unfurnished,3,2,114.8,174906.0,5549.0,9.9,...,93.5,2,Yes,No,Professional,Occupied,71.2,153825.0,174906.0,1345.430769
1,2,Karen,Apartment,Semi-Furnished,5,5,75.2,377170.0,3205.0,24.5,...,94.0,3,No,Yes,Professional,Occupied,89.4,336858.0,377170.0,2901.307692
2,3,Umoja,Apartment,Furnished,1,1,84.9,84013.0,4526.0,6.6,...,91.2,0,No,No,Student,Occupied,83.1,71889.0,84013.0,646.253846
3,4,Ruaka,Apartment,Unfurnished,2,3,75.2,151752.0,2496.0,17.9,...,98.6,2,No,Yes,Student,Occupied,65.4,137138.0,151752.0,1167.323077
4,5,Kasarani,Maisonette,Unfurnished,3,3,69.6,98368.0,999.0,3.6,...,94.0,2,No,No,Expat,Occupied,70.8,91765.0,98368.0,756.676923

__Handling null values__

In [104]:
df.isnull().sum()

id                        0
estate                    0
property_type             0
furnishing                0
bedrooms                  0
bathrooms                 0
floor_size_sqm            0
monthly_rent_kes          0
service_charge_kes       30
distance_to_cbd_km        0
age_of_building_years     0
security_rating          30
occupancy_rate            0
parking_slots             0
backup_generator          0
has_borehole              0
tenant_type               0
vacancy_status            0
satisfaction_score       30
rent_2024                 0
rent_2025                 0
monthly_rent_usd          0
dtype: int64

In [105]:
(30/2000) * 100

1.5

__Thresholds for missing values and handling missing values__  
_Thresholds_  
- Between 0% to 30/40% nulls  
    - Fill the nulls using mean, median(numerical features) subject to the distribution of the dataset.  
    - For the categorical features/columns fill with the mode.  

- More than 40%  
    - Drop the column  

- Less than 5% nulls/missing values  
    - Fill, drop the rows

In [106]:
print(f"{(30/2000)*100}%")

1.5%

In [107]:
df.isnull().sum()

id                        0
estate                    0
property_type             0
furnishing                0
bedrooms                  0
bathrooms                 0
floor_size_sqm            0
monthly_rent_kes          0
service_charge_kes       30
distance_to_cbd_km        0
age_of_building_years     0
security_rating          30
occupancy_rate            0
parking_slots             0
backup_generator          0
has_borehole              0
tenant_type               0
vacancy_status            0
satisfaction_score       30
rent_2024                 0
rent_2025                 0
monthly_rent_usd          0
dtype: int64

__Dropping Missing values__

In [108]:
# Dropping nulls from the whole dataset  
# df = df.dropna()

In [109]:
# Drop null/missing values from a specific column  
# df = df.dropna(subset=['service_charge_kes', 'security_rating'])

__Filling Nulls__

In [110]:
df.isnull().sum()

id                        0
estate                    0
property_type             0
furnishing                0
bedrooms                  0
bathrooms                 0
floor_size_sqm            0
monthly_rent_kes          0
service_charge_kes       30
distance_to_cbd_km        0
age_of_building_years     0
security_rating          30
occupancy_rate            0
parking_slots             0
backup_generator          0
has_borehole              0
tenant_type               0
vacancy_status            0
satisfaction_score       30
rent_2024                 0
rent_2025                 0
monthly_rent_usd          0
dtype: int64

In [111]:
# Filling nulls/Missing values for the satisfaction score  
df["satisfaction_score"] = df["satisfaction_score"].fillna(0)

In [112]:
# Filling nulls with mean  
mean_service_charge = df["service_charge_kes"].mean() 

print(f"Average service charge: {mean_service_charge}")  

df["service_charge_kes"] = df["service_charge_kes"].fillna(mean_service_charge)

Average service charge: 4991.145177664975

__Dealing wit duplicates__

In [113]:
# Checking for duplicates  
df.duplicated().sum()

np.int64(0)

In [114]:
# Assuming there are duplicates present, this is how yopu drop them  
df = df.drop_duplicates()

__Sorting Data__    
Sorting is arranging data in a specific order.

In [115]:
# Sorting from the smallest to the largest/ascending order
df.sort_values("bedrooms", ascending=True)

,id,estate,property_type,furnishing,bedrooms,bathrooms,floor_size_sqm,monthly_rent_kes,service_charge_kes,distance_to_cbd_km,...,occupancy_rate,parking_slots,backup_generator,has_borehole,tenant_type,vacancy_status,satisfaction_score,rent_2024,rent_2025,monthly_rent_usd
1349,1350,Kilimani,Apartment,Unfurnished,1,1,65.0,177433.0,1219.0,14.8,...,93.6,2,Yes,No,Expat,Occupied,87.4,163871.0,177433.0,1364.869231
544,545,Westlands,Maisonette,Semi-Furnished,1,1,104.6,254199.0,6910.0,13.9,...,92.7,1,No,Yes,Family,Occupied,60.4,216637.0,254199.0,1955.376923
1091,1092,Langata,Apartment,Semi-Furnished,1,2,86.8,141967.0,2956.0,10.8,...,88.1,1,Yes,Yes,Professional,Occupied,71.4,133045.0,141967.0,1092.053846
286,287,Westlands,Maisonette,Unfurnished,1,2,90.8,226778.0,5799.0,18.3,...,82.4,1,No,No,Expat,Vacant,65.7,197767.0,226778.0,1744.446154
540,541,Lavington,Apartment,Unfurnished,1,2,71.9,195553.0,6448.0,18.1,...,94.5,1,No,Yes,Family,Occupied,61.8,179634.0,195553.0,1504.253846
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
394,395,Kileleshwa,Maisonette,Unfurnished,6,6,108.3,330363.0,2438.0,16.5,...,93.9,3,Yes,No,Expat,Occupied,83.0,318438.0,330363.0,2541.253846
1520,1521,Westlands,Maisonette,Semi-Furnished,6,6,108.2,421174.0,3945.0,3.9,...,97.9,4,Yes,Yes,Family,Vacant,82.8,386220.0,421174.0,3239.800000
1226,1227,Karen,Apartment,Furnished,6,6,105.2,530054.0,4011.0,6.0,...,93.8,3,No,Yes,Family,Vacant,77.7,461046.0,530054.0,4077.338462
1531,1532,Ruaka,Bedsitter,Semi-Furnished,6,5,90.2,273354.0,8460.0,9.9,...,85.5,4,Yes,No,Family,Occupied,73.4,233201.0,273354.0,2102.723077
1345,1346,Runda,Maisonette,Furnished,6,6,81.5,527910.0,1571.0,13.7,...,86.4,4,No,Yes,Professional,Occupied,59.7,452472.0,527910.0,4060.846154

In [116]:
# Sorting in a descending order  
df.sort_values("parking_slots", ascending=False)

,id,estate,property_type,furnishing,bedrooms,bathrooms,floor_size_sqm,monthly_rent_kes,service_charge_kes,distance_to_cbd_km,...,occupancy_rate,parking_slots,backup_generator,has_borehole,tenant_type,vacancy_status,satisfaction_score,rent_2024,rent_2025,monthly_rent_usd
1466,1467,Karen,Maisonette,Semi-Furnished,5,4,95.8,487426.0,3437.0,7.6,...,86.8,4,Yes,No,Student,Occupied,51.0,462186.0,487426.0,3749.430769
145,146,Kileleshwa,Apartment,Semi-Furnished,5,6,96.3,309001.0,10863.0,7.9,...,93.9,4,No,No,Student,Vacant,79.2,262158.0,309001.0,2376.930769
147,148,Kasarani,Apartment,Furnished,5,5,101.2,144526.0,2381.0,3.1,...,92.8,4,No,No,Expat,Occupied,75.6,122658.0,144526.0,1111.738462
148,149,Runda,Townhouse,Semi-Furnished,4,4,82.9,456672.0,1739.0,12.6,...,93.8,4,Yes,No,Student,Occupied,79.7,399860.0,456672.0,3512.861538
908,909,Roysambu,Maisonette,Unfurnished,5,4,106.3,157633.0,1773.0,3.0,...,92.2,4,No,No,Student,Occupied,78.8,150639.0,157633.0,1212.561538
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1342,1343,Roysambu,Apartment,Furnished,1,1,80.2,94490.0,4666.0,2.3,...,88.4,0,No,Yes,Student,Occupied,60.9,80736.0,94490.0,726.846154
1173,1174,Kileleshwa,Apartment,Unfurnished,1,2,64.1,153259.0,2879.0,18.7,...,92.0,0,No,Yes,Family,Occupied,48.1,131424.0,153259.0,1178.915385
1682,1683,Runda,Maisonette,Furnished,1,1,86.8,339116.0,1865.0,4.2,...,80.9,0,No,Yes,Expat,Occupied,100.0,296411.0,339116.0,2608.584615
1782,1783,Langata,Apartment,Unfurnished,2,2,85.9,154449.0,4937.0,8.9,...,80.8,0,No,No,Student,Occupied,87.8,141197.0,154449.0,1188.069231
1489,1490,Kilimani,Apartment,Semi-Furnished,1,2,103.2,226178.0,1379.0,5.4,...,94.4,0,Yes,Yes,Expat,Occupied,77.5,207127.0,226178.0,1739.830769

## Summarising data
__Grouping Data__  
Grouping is used when we want to summarize data by category.   
```python  
df.groupby(categorical_column)[column you are working]  
```  

examples of operations you can do are:   
- counts .count()  
- averages .mean()  
- Middlemost .median()  
- totals    .sum()

In [117]:
# Grouping the data furnishing; total of each furnishing category  
df.groupby("furnishing")["furnishing"].count()

furnishing
Furnished          390
Semi-Furnished     603
Unfurnished       1007
Name: furnishing, dtype: int64

In [118]:
# Grouping the furnishing categories to get the average rent per category  
df.groupby("furnishing")["monthly_rent_kes"].mean()

furnishing
Furnished         223800.689744
Semi-Furnished    217437.203980
Unfurnished       226410.309831
Name: monthly_rent_kes, dtype: float64

In [119]:
# Average rent per property type  
df.groupby("property_type")["monthly_rent_kes"].mean()

property_type
Apartment     227291.952381
Bedsitter     207252.214521
Maisonette    222513.125301
Townhouse     226573.184211
Name: monthly_rent_kes, dtype: float64

__Value Counts__

In [120]:
# Count of each furnishing category
df["furnishing"].value_counts()

furnishing
Unfurnished       1007
Semi-Furnished     603
Furnished          390
Name: count, dtype: int64

In [121]:
# Count of each estate in the housing dataset  
df["estate"].value_counts()

estate
Westlands     159
Kileleshwa    146
Runda         143
Embakasi      142
Roysambu      142
South B       138
South C       135
Donholm       134
Ruaka         130
Umoja         128
Lavington     128
Langata       123
Kilimani      120
Karen         119
Kasarani      113
Name: count, dtype: int64

### Working with text data  
__Converting to lowercase__

In [122]:
# Converting property_type column to lowercase
df["property_type"] = df["property_type"].str.lower()
df.head()

,id,estate,property_type,furnishing,bedrooms,bathrooms,floor_size_sqm,monthly_rent_kes,service_charge_kes,distance_to_cbd_km,...,occupancy_rate,parking_slots,backup_generator,has_borehole,tenant_type,vacancy_status,satisfaction_score,rent_2024,rent_2025,monthly_rent_usd
0,1,South B,apartment,Unfurnished,3,2,114.8,174906.0,5549.0,9.9,...,93.5,2,Yes,No,Professional,Occupied,71.2,153825.0,174906.0,1345.430769
1,2,Karen,apartment,Semi-Furnished,5,5,75.2,377170.0,3205.0,24.5,...,94.0,3,No,Yes,Professional,Occupied,89.4,336858.0,377170.0,2901.307692
2,3,Umoja,apartment,Furnished,1,1,84.9,84013.0,4526.0,6.6,...,91.2,0,No,No,Student,Occupied,83.1,71889.0,84013.0,646.253846
3,4,Ruaka,apartment,Unfurnished,2,3,75.2,151752.0,2496.0,17.9,...,98.6,2,No,Yes,Student,Occupied,65.4,137138.0,151752.0,1167.323077
4,5,Kasarani,maisonette,Unfurnished,3,3,69.6,98368.0,999.0,3.6,...,94.0,2,No,No,Expat,Occupied,70.8,91765.0,98368.0,756.676923

__Converting to Uppercase__

In [123]:
df["property_type"] = df["property_type"].str.upper()
df.head()

,id,estate,property_type,furnishing,bedrooms,bathrooms,floor_size_sqm,monthly_rent_kes,service_charge_kes,distance_to_cbd_km,...,occupancy_rate,parking_slots,backup_generator,has_borehole,tenant_type,vacancy_status,satisfaction_score,rent_2024,rent_2025,monthly_rent_usd
0,1,South B,APARTMENT,Unfurnished,3,2,114.8,174906.0,5549.0,9.9,...,93.5,2,Yes,No,Professional,Occupied,71.2,153825.0,174906.0,1345.430769
1,2,Karen,APARTMENT,Semi-Furnished,5,5,75.2,377170.0,3205.0,24.5,...,94.0,3,No,Yes,Professional,Occupied,89.4,336858.0,377170.0,2901.307692
2,3,Umoja,APARTMENT,Furnished,1,1,84.9,84013.0,4526.0,6.6,...,91.2,0,No,No,Student,Occupied,83.1,71889.0,84013.0,646.253846
3,4,Ruaka,APARTMENT,Unfurnished,2,3,75.2,151752.0,2496.0,17.9,...,98.6,2,No,Yes,Student,Occupied,65.4,137138.0,151752.0,1167.323077
4,5,Kasarani,MAISONETTE,Unfurnished,3,3,69.6,98368.0,999.0,3.6,...,94.0,2,No,No,Expat,Occupied,70.8,91765.0,98368.0,756.676923

__Removing Spaces__

In [ ]:
df["estate"] = df["estate"].str.strip()        
df.head()

,id,estate,property_type,furnishing,bedrooms,bathrooms,floor_size_sqm,monthly_rent_kes,service_charge_kes,distance_to_cbd_km,...,occupancy_rate,parking_slots,backup_generator,has_borehole,tenant_type,vacancy_status,satisfaction_score,rent_2024,rent_2025,monthly_rent_usd
0,1,South B,APARTMENT,Unfurnished,3,2,114.8,174906.0,5549.0,9.9,...,93.5,2,Yes,No,Professional,Occupied,71.2,153825.0,174906.0,1345.430769
1,2,Karen,APARTMENT,Semi-Furnished,5,5,75.2,377170.0,3205.0,24.5,...,94.0,3,No,Yes,Professional,Occupied,89.4,336858.0,377170.0,2901.307692
2,3,Umoja,APARTMENT,Furnished,1,1,84.9,84013.0,4526.0,6.6,...,91.2,0,No,No,Student,Occupied,83.1,71889.0,84013.0,646.253846
3,4,Ruaka,APARTMENT,Unfurnished,2,3,75.2,151752.0,2496.0,17.9,...,98.6,2,No,Yes,Student,Occupied,65.4,137138.0,151752.0,1167.323077
4,5,Kasarani,MAISONETTE,Unfurnished,3,3,69.6,98368.0,999.0,3.6,...,94.0,2,No,No,Expat,Occupied,70.8,91765.0,98368.0,756.676923

__Checking if text contains__

In [125]:
# Checking if estate column contains  Kasarani, Mombasa  

df[df["estate"].str.contains("Kasarani")]

,id,estate,property_type,furnishing,bedrooms,bathrooms,floor_size_sqm,monthly_rent_kes,service_charge_kes,distance_to_cbd_km,...,occupancy_rate,parking_slots,backup_generator,has_borehole,tenant_type,vacancy_status,satisfaction_score,rent_2024,rent_2025,monthly_rent_usd
4,5,Kasarani,MAISONETTE,Unfurnished,3,3,69.6,98368.0,999.0,3.6,...,94.0,2,No,No,Expat,Occupied,70.8,91765.0,98368.0,756.676923
12,13,Kasarani,TOWNHOUSE,Semi-Furnished,5,4,71.6,138060.0,6783.0,8.9,...,94.1,3,Yes,No,Family,Occupied,69.4,119228.0,138060.0,1062.000000
13,14,Kasarani,APARTMENT,Furnished,6,6,61.2,127332.0,4177.0,6.4,...,84.1,4,Yes,No,Family,Occupied,68.6,117803.0,127332.0,979.476923
38,39,Kasarani,MAISONETTE,Semi-Furnished,2,3,102.6,117889.0,7192.0,11.1,...,95.3,1,Yes,Yes,Student,Occupied,77.4,111920.0,117889.0,906.838462
39,40,Kasarani,BEDSITTER,Unfurnished,3,3,83.8,105489.0,4994.0,4.5,...,82.4,1,No,Yes,Student,Occupied,91.4,93646.0,105489.0,811.453846
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1928,1929,Kasarani,APARTMENT,Unfurnished,3,4,88.8,100899.0,2937.0,6.3,...,94.9,2,No,No,Professional,Occupied,80.5,94684.0,100899.0,776.146154
1938,1939,Kasarani,MAISONETTE,Semi-Furnished,4,3,78.3,166643.0,7112.0,14.5,...,84.1,3,Yes,Yes,Expat,Occupied,86.1,149045.0,166643.0,1281.869231
1952,1953,Kasarani,APARTMENT,Furnished,4,5,78.6,141134.0,3859.0,7.9,...,96.3,2,No,Yes,Professional,Occupied,83.0,128013.0,141134.0,1085.646154
1979,1980,Kasarani,APARTMENT,Unfurnished,2,2,71.1,94278.0,5087.0,7.3,...,92.7,2,Yes,Yes,Expat,Occupied,69.9,80543.0,94278.0,725.215385
1985,1986,Kasarani,APARTMENT,Semi-Furnished,2,2,76.1,91051.0,22697.0,1.3,...,91.7,1,No,No,Student,Occupied,71.2,86903.0,91051.0,700.392308

### Working with Dates

In [126]:
# Reading the dataset
dates_df = pd.read_csv(r"../statistics/orders.csv")  

dates_df.head()

,order_id,customer_name,order_date,delivery_date,last_login,subscription_start
0,1001,Alice,2025-01-05,2025-01-08,2025-01-05 08:15:22,2024-06-15
1,1002,Bob,2025-01-12,2025-01-15,2025-01-12 14:30:45,2024-07-20
2,1003,Charlie,2025-02-03,2025-02-07,2025-02-03 09:12:10,2024-08-01
3,1004,Diana,2025-02-18,2025-02-21,2025-02-18 18:45:33,2024-09-10
4,1005,Ethan,2025-03-01,2025-03-05,2025-03-01 07:05:12,2024-10-05

In [127]:
# Check how the dates have been read  
dates_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 13 entries, 0 to 12
Data columns (total 6 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   order_id            13 non-null     int64
 1   customer_name       13 non-null     object
 2   order_date          13 non-null     object
 3   delivery_date       13 non-null     object
 4   last_login          13 non-null     object
 5   subscription_start  13 non-null     object
dtypes: int64(1), object(5)
memory usage: 756.0+ bytes

__Converting object dates to date data type__

In [129]:
# Converting order_date  
dates_df["order_date"] = pd.to_datetime(dates_df["order_date"], errors = 'coerce')  
dates_df.info() 
# # dates_df["delivery_date"] = pd.to_datetime(dates_df["delivery_date"], errors='coerce')  
# dates_df.info()  

dates_columns = ["order_date", "delivery_date", "last_login"]  

# for column in dates_columns:
#     dates_df[column] = pd.to_datetime(dates_df[column], errors='coerce') 

# dates_df.info()

# YYYY/MM/DD
# YYYY/Max(12)/Max(31)
# YYYY/18/13

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 13 entries, 0 to 12
Data columns (total 6 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   order_id            13 non-null     int64
 1   customer_name       13 non-null     object
 2   order_date          12 non-null     datetime64[ns]
 3   delivery_date       13 non-null     object
 4   last_login          13 non-null     object
 5   subscription_start  13 non-null     object
dtypes: datetime64[ns](1), int64(1), object(4)
memory usage: 756.0+ bytes

In [130]:
dates_df

,order_id,customer_name,order_date,delivery_date,last_login,subscription_start
0,1001,Alice,2025-01-05,2025-01-08,2025-01-05 08:15:22,2024-06-15
1,1002,Bob,2025-01-12,2025-01-15,2025-01-12 14:30:45,2024-07-20
2,1003,Charlie,2025-02-03,2025-02-07,2025-02-03 09:12:10,2024-08-01
3,1004,Diana,2025-02-18,2025-02-21,2025-02-18 18:45:33,2024-09-10
4,1005,Ethan,2025-03-01,2025-03-05,2025-03-01 07:05:12,2024-10-05
5,1006,Faith,2025-03-15,2025-03-20,2025-03-15 12:55:41,2024-11-12
6,1007,George,2025-04-02,2025-04-06,2025-04-02 16:20:05,2024-12-01
7,1008,Hannah,2025-04-20,2025-04-24,2025-04-20 10:40:18,2025-01-15
8,1009,Ian,2025-05-10,2025-05-13,2025-05-10 20:10:55,2025-02-01
9,1010,Jane,2025-05-25,2025-05-29,2025-05-25 11:35:27,2025-03-10
10,1011,Kevin,2025-06-08,2025-06-11,2025-06-08 06:50:44,2025-04-05
11,1012,Lisa,2025-06-22,2025-06-26,2025-06-22 22:15:30,2025-05-01
12,1013,Emmanuel,NaT,2025-06-23,2025-07-01 09:15:23,2025-09-02

#### Extracting the Year, Month, Day  
__a). Extracting the year__

In [ ]:
# Extracting the year  
dates_df["Order_year"] = dates_df["order_date"].dt.year

dates_df.head()

,order_id,customer_name,order_date,delivery_date,last_login,subscription_start,Year,Order_year
0,1001,Alice,2025-01-05,2025-01-08,2025-01-05 08:15:22,2024-06-15,2025,2025
1,1002,Bob,2025-01-12,2025-01-15,2025-01-12 14:30:45,2024-07-20,2025,2025
2,1003,Charlie,2025-02-03,2025-02-07,2025-02-03 09:12:10,2024-08-01,2025,2025
3,1004,Diana,2025-02-18,2025-02-21,2025-02-18 18:45:33,2024-09-10,2025,2025
4,1005,Ethan,2025-03-01,2025-03-05,2025-03-01 07:05:12,2024-10-05,2025,2025

__b). Extracting the month__

In [ ]:
# Extracting the order month  
dates_df["Order_month"] = dates_df["order_date"].dt.month

dates_df.head()

,order_id,customer_name,order_date,delivery_date,last_login,subscription_start,Year,Order_year,Order_month
0,1001,Alice,2025-01-05,2025-01-08,2025-01-05 08:15:22,2024-06-15,2025,2025,1
1,1002,Bob,2025-01-12,2025-01-15,2025-01-12 14:30:45,2024-07-20,2025,2025,1
2,1003,Charlie,2025-02-03,2025-02-07,2025-02-03 09:12:10,2024-08-01,2025,2025,2
3,1004,Diana,2025-02-18,2025-02-21,2025-02-18 18:45:33,2024-09-10,2025,2025,2
4,1005,Ethan,2025-03-01,2025-03-05,2025-03-01 07:05:12,2024-10-05,2025,2025,3

__c) Extracting the day__

In [ ]:
# Exracting the order day  
dates_df["Order_Day"] = dates_df["order_date"].dt.day  

dates_df.head()

,order_id,customer_name,order_date,delivery_date,last_login,subscription_start,Year,Order_year,Order_month,Order_Day
0,1001,Alice,2025-01-05,2025-01-08,2025-01-05 08:15:22,2024-06-15,2025,2025,1,5
1,1002,Bob,2025-01-12,2025-01-15,2025-01-12 14:30:45,2024-07-20,2025,2025,1,12
2,1003,Charlie,2025-02-03,2025-02-07,2025-02-03 09:12:10,2024-08-01,2025,2025,2,3
3,1004,Diana,2025-02-18,2025-02-21,2025-02-18 18:45:33,2024-09-10,2025,2025,2,18
4,1005,Ethan,2025-03-01,2025-03-05,2025-03-01 07:05:12,2024-10-05,2025,2025,3,1